name: bug-b
base: core22
version: '0.1'
summary: B
description: B
grade: stable
confinement: strict

plugs:
  my-interface:
    interface: content
    target: $SNAP_DATA/import

apps:
  bug-b:
    command: bug-b
    plugs: [my-interface]

parts:
  application:
    source: files
    plugin: dump
